== Activité I - Rédiger des User Story

=== Introduction

==== Objectifs

- Se confronter aux problèmes que soulève la traduction d'un cahier des charges d'un client en quelque chose d'exploitable par une équipe de développement.
- Rédiger des *User Stories*.

==== Modalités

Alternance de travail en binôme et individuel sur étude de cas.

==== Le cas du site de "L'Alliance pour l'Ostéopathie Autrement".

Vous êtes "consultant fonctionnel" au sein d'une agence web. On vient de vous confier un nouveau projet consistant à développer le site Web de "L'Alliance pour l'Ostéopathie Autrement" (ALOSA). Vous êtes donc le ou la consultant•e fonctionnel•le côté maitrise d'œuvre sur ce projet. Le projet doit se dérouler en mode agile en utilisant la méthode Scrum. Dans le jargon Scrum, vous êtes donc le Product Owner. En tant que Product Owner, votre rôle est de fournir de toutes les manières possibles les informations permettant à l'équipe de développement de développer le site Internet ALOSA.

Le cahier des charges fourni par le client est disponible dans les ressources de l'activité.

=== Premiers pas dans le rôle de Product Owner

==== Lecture active du cahier des charges

1. Lisez individuellement le cahier des charges en relevant toutes les questions et remarques que celui suscite, toujours dans l'idée de pouvoir transmettre le maximum d'éléments permettant à l'équipe de développement de faire le travail.
2. Mettez en commun vos questions et remarques avec votre binôme.

====  Questions/Réponses

https://cours22-23.ut-capitole.fr/course/view.php?id=14299[Activité elaastic : Du CDC au développement...]

NOTE: Vous pouvez réfléchir en binôme, mais les réponses fournies doivent être individuelles.

=== Rédaction des Users Stories

==== Étude d'exemples

Le document "example-user-stories.pdf" disponible dans les ressources contient l'ensembles des US qui ont été écrite pour la réalisation de la première version du site de l'Alliance Agile.

Parmi les US, dans partie "Courses and Events", certaines US sont surlignées en vert, d'autres en orange.

https://cours22-23.ut-capitole.fr/course/view.php?id=14299[Activité elaastic : Exemples de *User stories*...]

==== Création du board Zenhub

Pour cette activité, vous aurez besoin d'utiliser votre compte Github.

1.  Inscrivez-vous au devoir Site_Alosa via Github Classroom et RDV sur le projet créé.
https://cours22-23.ut-capitole.fr/course/view.php?id=14299[Lien d'inscription Github Classroom]

NOTE: Coordonnez-vous au sein du binôme pour vous inscrire dans la même *team* pour partager le même projet.

[start=2]
. Installez l'extension Zenhub pour votre navigateur préféré. Une fois l'extension installée, cliquez sur l'onglet Zenhub disposnible dans le projet Github "Site_Alosa".
. Explorez librement les possibilités de gestion d'un *board Zenhub*.
. Renommez, si nécessaire la première colonne en "Product backlog".


==== Rédaction d'US pour le site ALOSA 

1. Au sein de votre binôme, répartissez vous 1 partie du site ALOSA à spécifier sous forme d'US.
2. Directement dans le board Zenhub du projet : 
    - Créez une *epic* correspondant à la partie que vous devez spécifier.
    - Rédigez 6 US attachées à cette *epic* (1 issue par US dans la colonne "backlog"). 
3. Relisez les US écrites par votre binôme en notant vos questions et vos remarques sur ces US que vous n'avez pas écrites.
4. Échangez avec votre binôme pour finaliser l'écriture des 12 US qui ont été rédigées.